### ISSUE TITLE
Bootstrapping DSC Resources

### ISSUE THREAD

**Issue by iainbrighton** [VirtualEngine/Lab#21]
The DSC configuration data document (.psd1) could be extended to include the required DSC resources and these could be downloaded if not present on the host system. 

For example:
```powershell
NonNodeData = @{
    VirtualEngineLab = @{
        DSCResource = @(
            @{ ModuleName = 'xNetworking'; MiniumumVersion = '2.4.0.0'; }
        );
    }
}
```
The Powershell Gallery is ripe for this but only includes the 'master' branch. There is also no guarantee that OneGet is installed on the Host system either..

The https://github.com/iainbrighton/GitHubRepository module could be used to automatically download missing DSC resources regardless of branch, owner or whether they're published to the gallery?

__Note: the 'Resource' keyword is already used for custom resources.__

**Comment by csandfeld** [comment]
Not sure if this warrants a seperate topic, but I have run into a problem with modules installed using PowerShell 5's Install-Module Cmdlet.

Scenario:
Host OS is Windows 10.
Modules xComputerManagement, xNetworking etc. were installed with the Install-Module Cmdlet, causing the modules to have a folder structure including the modules version number.

As an example, the xComputerManagement module resides in the C:\Program Files\WindowsPowerShell\Modules\xComputerManagement\1.3.0 folder.

Now when I create a lab with Windows Server 2012R2 or Windows 8.1 VM’s, they get stuck in the bootstrap process, when trying to apply the DSC configuration. Reviewing the log shows that it cannot find the DSC resources.

Moving the modules out of the “version subfolder” fixes that. This makes sense since support for multiple versions of a module (and thus the “version subfolder”) is introduced with PowerShell 5.

It would be great if that could be taken into consideration, when resources are copied into VM disk.

**Comment by iainbrighton** [comment]
In theory Modules could be downloaded directly from https://powershellgallery.com as it's just a Nuget feed and the .nupkg files are glorified .ZIP files. Versioned modules are also available here...
